### ISSUE TITLE
support proxy

### ISSUE THREAD

**Issue by neatlife** [niutech/amp-browser#1]
Could you add feature to support custom proxy.

**Comment by niutech** [comment]
Hello!
What do you mean by a custom proxy? You cannot use another one when
using the Data Compression Proxy.

**Comment by neatlife** [comment]
@niutech The Data Compression Proxy is blocked from china, how to solve the problem.

**Comment by niutech** [comment]
You can disable the Data Compression Proxy by deleting the command line switch `--enable-spdy-proxy-auth` in _chrlauncher.ini_.

**Comment by neatlife** [comment]
@niutech but when disable the Data Compression Proxy, Is the amp remind working?

**Comment by niutech** [comment]
Yes, the AMP will work fine with or without proxy.
